import type { FiammaBook } from '@/types/fiamma'

export const localFiammaBooks: FiammaBook[] = [
  {
    title_id: 'akm-001-terms-and-conditions',
    title: 'Terms and Conditions: A Novel',
    slug: 'terms-and-conditions',
    heteronym: 'Aubrey Kenneth Moss',
    imprint: 'fiamma-spark',
    imprint_subline: 'The ache of the build. The tension that makes you want to scream at the characters to just do it already. It is slow, it is painful, and it is always worth the wait.',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      'A novel about a corporate attorney and a tech founder navigating the verifiable three inches between proof and promise.',
    blurb_300:
      "Berna Alvarez is a corporate liability attorney who believes in proof, not promises. Sam Reyes is a tech founder who builds mobility solutions that Berna's firm would rather litigate out of existence. When an asbestos-induced exile forces Berna into the shared workspace of Sam's start-up, the resulting collision of legal risk and technological optimism creates a friction that neither can document away. 'Terms and Conditions' is a novel about the small, verifiable distance between two people who know exactly who the other is, and choose to bridge it anyway.",
    cover_url: '/assets/covers/terms-and-conditions.jpg',
    isbn_pb: '978-1-917717-24-3',
    isbn_eb: '978-1-917717-25-0',
    isbn_audio: '978-1-917717-26-7',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 1,
    visible: true,
    created_at: '2026-03-03T00:00:00Z',
    updated_at: '2026-04-23T00:00:00Z',
  },
  {
    title_id: 'akm-002-field-study',
    title: 'Field Study',
    slug: 'field-study',
    heteronym: 'Aubrey Kenneth Moss',
    imprint: 'fiamma-spark',
    imprint_subline: 'The ache of the build. The tension that makes you want to scream at the characters to just do it already. It is slow, it is painful, and it is always worth the wait.',
    genre: 'Romance',
    fiamma_line: 'Literary',
    blurb_short:
      'A novel about a scientist who applies the discipline of field science to the least tractable data problem she has ever encountered: a man she cannot classify.',
    blurb_300:
      "Wren Mitchell is a scientist. She observes, measures, and records. She does not declare findings before the data is complete. After a vestibular injury ended her NASA career, she built a life at a research station in Pacific Grove. What she does not have a methodology for is her colleague Owen Reid. Wren starts keeping a field notebook. Not for him. She has always kept field notebooks. But she begins making marks in the margin, small tick marks with no labels, every time Owen says something that turns out to be exactly right. 'Field Study' is a novel about a woman who stopped reaching, and about what happens when the data finally becomes undeniable.",
    cover_url: '/assets/covers/field-study.jpg',
    isbn_pb: '978-1-917717-27-4',
    isbn_eb: '978-1-917717-28-1',
    isbn_audio: '978-1-917717-29-8',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 2,
    visible: true,
    created_at: '2026-03-09T00:00:00Z',
    updated_at: '2026-04-23T00:00:00Z',
  },
  {
    title_id: 'akm-003-base-notes',
    title: 'Base Notes',
    slug: 'base-notes',
    heteronym: 'Aubrey Kenneth Moss',
    imprint: 'fiamma-spark',
    imprint_subline: 'The ache of the build. The tension that makes you want to scream at the characters to just do it already. It is slow, it is painful, and it is always worth the wait.',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      'Margot Crane is a perfumer with a nose that can identify three thousand compounds and a debt that is eating her studio alive.',
    blurb_300:
      "Margot Crane can identify over three thousand aromatic compounds. She can tell you what soap you used this morning, what you ate for lunch, and whether you're nervous. She is very good at her job and she is about to lose her studio. Two hundred and three thousand pounds in debt after a conglomerate gutted her contract, Margot flies to Positano with forty thousand euros of vintage oud on her lap to compete for a commission that could keep her afloat. The residency is two weeks. The competitors are Edouard Pelletier, a sixty-one-year-old French perfumer who irons his own shirts and has nothing left to prove, and Leo Vance, an independent from New York whose heart accord Margot has written about in print and whose base note she cannot identify. That has never happened to her before. For fourteen days, Margot works through a partition wall from a man she can hear but not read. She can smell his soap, his laundered cotton, the top notes and the heart of whatever he is building. But the base, the part of a fragrance that tells you who someone actually is, comes back blank. Every time. The competition has a fee that could change her life. The proximity has a cost she did not budget for. And the answer to why she cannot read Leo Vance is closer than she thinks, built into the architecture of her own formula, hiding in the one place a perfumer's nose cannot reach. Base Notes is a novel about work and want and the specific chemistry of two people who found the same raw material from different directions. It is a love story told through the nose of a woman who would rather profile your cologne than admit she is falling for you.",
    cover_url: '/assets/covers/base-notes.jpg',
    isbn_pb: '978-1-917717-41-0',
    isbn_eb: '978-1-917717-42-7',
    isbn_audio: '978-1-917717-43-4',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 3,
    visible: true,
    created_at: '2026-03-12T00:00:00Z',
    updated_at: '2026-04-22T00:00:00Z',
  },
  {
    title_id: 'hailey-boone-001-mud-season',
    title: 'Mud Season',
    slug: 'mud-season',
    heteronym: 'Hailey Boone',
    imprint: 'fiamma-contemporary',
    imprint_subline: 'Stories for right now. No waiting, no permission, just the heat that happens when two people stop pretending they do not want it.',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      "Juniper McClaren flew to Montana to close an estate, not to fall in love with the man on the porch. Three weeks to sell her grandfather's ranch. One foreman who fills a doorway, keeps a list of every small thing she pretends to know, and has a hand that already knows where a dog's shoulder is. She makes it thirty yards in grey heels before the mud takes both shoes. He doesn't come meet her halfway.",
    blurb_300:
      "Juniper McClaren flew to Montana to close an estate, not to fall in love with the man on the porch.\n\nSeattle litigator, eleven months unclaimed, twenty-one days to bury a grandfather she never knew — June arrives at McClaren Ranch in grey heels and a pantsuit and walks across thirty yards of April mud in her socks because the man at the top of the steps is not going to meet her halfway.\n\nWyatt Reeves runs the ranch and fills a doorway. He keeps a list, in his head, of every small thing she pretends to know.\n\nFor three weeks they fight about a cow and make up in a tack room. They kiss at a kitchen sink with grass still in her hair. He almost tells her what he wants, and she almost stays, and then a bank statement at the back of a mudroom cabinet blows it all apart.\n\nWhen she drunk-texts him I HATE YOU from an airport bar in a blizzard, he drives two hundred miles through a late-April whiteout to carry her home.\n\nBook one of Hailey Boone's Paradise Valley — for readers of Kristen Ashley, Maisey Yates, and Lauren Landish. Fun, hot, and honest about what it costs to let someone hand you the truth on a Tuesday.",
    cover_url: '/assets/covers/mud-season.jpg',
    isbn_pb: '978-1-917717-44-1',
    isbn_eb: '978-1-917717-45-8',
    isbn_audio: null,
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 1,
    visible: true,
    created_at: '2026-04-23T00:00:00Z',
    updated_at: '2026-04-23T18:00:00Z',
  },
  {
    title_id: 'hailey-boone-002-heat-wave',
    title: 'Heat Wave',
    slug: 'heat-wave',
    heteronym: 'Hailey Boone',
    imprint: 'fiamma-contemporary',
    imprint_subline: 'Stories for right now. No waiting, no permission, just the heat that happens when two people stop pretending they do not want it.',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      'Deb Reeves came to Paradise Valley for six days of sun, beer, and water, not for the man across the county road.',
    blurb_300:
      'Deb Reeves came to Paradise Valley for six days of sun, beer, and water, not for the man across the county road.\n\nShe is forty-five, freshly on vacation, and absolutely not looking to solve anything. Then the ranch AC dies on day one, the weather climbs past a hundred, and Cash Hollander appears at the back door in a soaked T-shirt and jean cutoffs with a bucket of iced beer and the kind of grin a woman ought to avoid on principle.\n\nCash runs the ranch next door. He is forty-six, widowed two years, raising a teenage son, and very committed to saying he is doing just fine. Deb does not believe him, which is half the problem. The other half is the swimming hole, the barn dance, the midnight skinny-dip, the fan pointed at the bed, and the fact that every time she rebooks her flight home, Cash shows up the next morning like he had a feeling.\n\nHeat Wave is Paradise Valley book two: hot, funny, grown-up romance for readers of Kristen Ashley, Maisey Yates, and Lauren Landish. Summer weather, adult bad decisions, and two people who were only supposed to have a week.',
    cover_url: '/assets/covers/heat-wave.jpg',
    isbn_pb: '978-1-917717-46-5',
    isbn_eb: '978-1-917717-47-2',
    isbn_audio: '978-1-917717-48-9',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 2,
    visible: true,
    created_at: '2026-04-30T00:00:00Z',
    updated_at: '2026-04-30T00:00:00Z',
  },
  {
    title_id: 'hailey-boone-003-bar-fight',
    title: 'Bar Fight',
    slug: 'bar-fight',
    heteronym: 'Hailey Boone',
    imprint: 'fiamma-contemporary',
    imprint_subline: 'Stories for right now. No waiting, no permission, just the heat that happens when two people stop pretending they do not want it.',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      "Molly Henderson came to Paradise Valley to sell her uncle's cabin and drive back to her bar in Livingston by Saturday night.",
    blurb_300:
      "Molly Henderson drove up to Paradise Valley for forty-eight hours to sell her uncle's cabin and drive back to her bar in Livingston by Saturday night.\n\nInstead she found Sawyer Wrangel on the roof, replacing shingles like he belonged there. Which, inconveniently, he does. Cal rented him the cabin six months ago. Sawyer has a lease through February, a truck under the cottonwoods, and no intention of moving because the woman with the U-Haul and the temper says she has plans.\n\nMolly owns The Bad Penny, a Livingston bar held together by regulars, stubbornness, and whatever she can still fix with her own two hands. Sawyer is a former fire-jumper who walked out of last year's season and landed in Paradise Valley because quiet looked better than smoke. She picks a fight instead of asking a question. He says he is fine about the one thing he is not fine about. By the time the first frost hits and the cabin's single bed starts making decisions for them, neither of them is operating on the plan they brought.\n\nBar Fight is Paradise Valley book three: autumn weather, one-bed tension, bar-owner competence, and four explicit scenes for readers of Kristen Ashley, Maisey Yates, and Lauren Landish.",
    cover_url: '/assets/covers/bar-fight.jpg',
    isbn_pb: '978-1-917717-49-6',
    isbn_eb: '978-1-917717-50-2',
    isbn_audio: '978-1-917717-51-9',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 3,
    visible: true,
    created_at: '2026-04-30T00:00:00Z',
    updated_at: '2026-04-30T00:00:00Z',
  },
]
