import type { FiammaBook } from '@/types/fiamma'

export const localFiammaBooks: FiammaBook[] = [
  {
    title_id: 'akm-001-terms-and-conditions',
    title: 'Terms and Conditions: A Novel',
    slug: 'terms-and-conditions',
    heteronym: 'Aubrey Kenneth Moss',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      'A novel about a corporate attorney and a tech founder navigating the verifiable three inches between proof and promise.',
    blurb_300:
      "Berna Alvarez is a corporate liability attorney who believes in proof, not promises. Sam Reyes is a tech founder who builds mobility solutions that Berna's firm would rather litigate out of existence. When an asbestos-induced exile forces Berna into the shared workspace of Sam's start-up, the resulting collision of legal risk and technological optimism creates a friction that neither can document away. 'Terms and Conditions' is a novel about the small, verifiable distance between two people who know exactly who the other is, and choose to bridge it anyway.",
    cover_url: '/assets/covers/terms-and-conditions.jpg',
    isbn_pb: '978-1-917717-24-3',
    isbn_eb: '978-1-917717-25-0',
    isbn_audio: '978-1-917717-26-7',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 1,
    visible: true,
    created_at: '2026-03-03T00:00:00Z',
    updated_at: '2026-04-23T00:00:00Z',
  },
  {
    title_id: 'akm-002-field-study',
    title: 'Field Study',
    slug: 'field-study',
    heteronym: 'Aubrey Kenneth Moss',
    genre: 'Romance',
    fiamma_line: 'Literary',
    blurb_short:
      'A novel about a scientist who applies the discipline of field science to the least tractable data problem she has ever encountered: a man she cannot classify.',
    blurb_300:
      "Wren Mitchell is a scientist. She observes, measures, and records. She does not declare findings before the data is complete. After a vestibular injury ended her NASA career, she built a life at a research station in Pacific Grove. What she does not have a methodology for is her colleague Owen Reid. Wren starts keeping a field notebook. Not for him. She has always kept field notebooks. But she begins making marks in the margin, small tick marks with no labels, every time Owen says something that turns out to be exactly right. 'Field Study' is a novel about a woman who stopped reaching, and about what happens when the data finally becomes undeniable.",
    cover_url: '/assets/covers/field-study.jpg',
    isbn_pb: '978-1-917717-27-4',
    isbn_eb: '978-1-917717-28-1',
    isbn_audio: '978-1-917717-29-8',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 2,
    visible: true,
    created_at: '2026-03-09T00:00:00Z',
    updated_at: '2026-04-23T00:00:00Z',
  },
  {
    title_id: 'akm-003-base-notes',
    title: 'Base Notes',
    slug: 'base-notes',
    heteronym: 'Aubrey Kenneth Moss',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      'Margot Crane is a perfumer with a nose that can identify three thousand compounds and a debt that is eating her studio alive.',
    blurb_300:
      "Margot Crane can identify over three thousand aromatic compounds. She can tell you what soap you used this morning, what you ate for lunch, and whether you're nervous. She is very good at her job and she is about to lose her studio. Two hundred and three thousand pounds in debt after a conglomerate gutted her contract, Margot flies to Positano with forty thousand euros of vintage oud on her lap to compete for a commission that could keep her afloat. The residency is two weeks. The competitors are Edouard Pelletier, a sixty-one-year-old French perfumer who irons his own shirts and has nothing left to prove, and Leo Vance, an independent from New York whose heart accord Margot has written about in print and whose base note she cannot identify. That has never happened to her before. For fourteen days, Margot works through a partition wall from a man she can hear but not read. She can smell his soap, his laundered cotton, the top notes and the heart of whatever he is building. But the base, the part of a fragrance that tells you who someone actually is, comes back blank. Every time. The competition has a fee that could change her life. The proximity has a cost she did not budget for. And the answer to why she cannot read Leo Vance is closer than she thinks, built into the architecture of her own formula, hiding in the one place a perfumer's nose cannot reach. Base Notes is a novel about work and want and the specific chemistry of two people who found the same raw material from different directions. It is a love story told through the nose of a woman who would rather profile your cologne than admit she is falling for you.",
    cover_url: '/assets/covers/base-notes.jpg',
    isbn_pb: '978-1-917717-41-0',
    isbn_eb: '978-1-917717-42-7',
    isbn_audio: '978-1-917717-43-4',
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 3,
    visible: true,
    created_at: '2026-03-12T00:00:00Z',
    updated_at: '2026-04-22T00:00:00Z',
  },
  {
    title_id: 'ellie-marsh-001-mud-season',
    title: 'Mud Season',
    slug: 'mud-season',
    heteronym: 'Ellie Marsh',
    genre: 'Romance',
    fiamma_line: 'Contemporary',
    blurb_short:
      "Juniper McClaren flew to Montana to close an estate, not to fall in love with the man on the porch. Three weeks to sell her grandfather's ranch. One foreman who fills a doorway, keeps a list of every small thing she pretends to know, and has a hand that already knows where a dog's shoulder is. She makes it thirty yards in grey heels before the mud takes both shoes. He doesn't come meet her halfway.",
    blurb_300:
      "Juniper McClaren flew to Montana to close an estate, not to fall in love with the man on the porch.\n\nSeattle litigator, eleven months unclaimed, twenty-one days to bury a grandfather she never knew — June arrives at McClaren Ranch in grey heels and a pantsuit and walks across thirty yards of April mud in her socks because the man at the top of the steps is not going to meet her halfway.\n\nWyatt Reeves runs the ranch and fills a doorway. He keeps a list, in his head, of every small thing she pretends to know.\n\nFor three weeks they fight about a cow and make up in a tack room. They kiss at a kitchen sink with grass still in her hair. He almost tells her what he wants, and she almost stays, and then a bank statement at the back of a mudroom cabinet blows it all apart.\n\nWhen she drunk-texts him I HATE YOU from an airport bar in a blizzard, he drives two hundred miles through a late-April whiteout to carry her home.\n\nBook one of Ellie Marsh's Paradise Valley — for readers of Kristen Ashley, Maisey Yates, and Lauren Landish. Fun, hot, and honest about what it costs to let someone hand you the truth on a Tuesday.",
    cover_url: '/assets/covers/mud-season.jpg',
    isbn_pb: '978-1-917717-44-1',
    isbn_eb: '978-1-917717-45-8',
    isbn_audio: null,
    buy_url_amazon: null,
    buy_url_ebook: null,
    buy_url_audio: null,
    series_order: 1,
    visible: true,
    created_at: '2026-04-23T00:00:00Z',
    updated_at: '2026-04-23T18:00:00Z',
  },
]
