INSERT INTO public.fiamma_books (
  title_id,
  title,
  slug,
  heteronym,
  genre,
  fiamma_line,
  blurb_short,
  blurb_300,
  cover_url,
  isbn_pb,
  isbn_eb,
  isbn_audio,
  series_order,
  visible
)
VALUES
  (
    'hailey-boone-002-heat-wave',
    'Heat Wave',
    'heat-wave',
    'Hailey Boone',
    'Romance',
    'Contemporary',
    'Deb Reeves came to Paradise Valley for six days of sun, beer, and water, not for the man across the county road.',
    'Deb Reeves came to Paradise Valley for six days of sun, beer, and water, not for the man across the county road.\n\nShe is forty-five, freshly on vacation, and absolutely not looking to solve anything. Then the ranch AC dies on day one, the weather climbs past a hundred, and Cash Hollander appears at the back door in a soaked T-shirt and jean cutoffs with a bucket of iced beer and the kind of grin a woman ought to avoid on principle.\n\nCash runs the ranch next door. He is forty-six, widowed two years, raising a teenage son, and very committed to saying he is doing just fine. Deb does not believe him, which is half the problem. The other half is the swimming hole, the barn dance, the midnight skinny-dip, the fan pointed at the bed, and the fact that every time she rebooks her flight home, Cash shows up the next morning like he had a feeling.\n\nHeat Wave is Paradise Valley book two: hot, funny, grown-up romance for readers of Kristen Ashley, Maisey Yates, and Lauren Landish. Summer weather, adult bad decisions, and two people who were only supposed to have a week.',
    '/assets/covers/heat-wave.jpg',
    '978-1-917717-46-5',
    '978-1-917717-47-2',
    '978-1-917717-48-9',
    2,
    true
  ),
  (
    'hailey-boone-003-bar-fight',
    'Bar Fight',
    'bar-fight',
    'Hailey Boone',
    'Romance',
    'Contemporary',
    'Molly Henderson came to Paradise Valley to sell her uncle''s cabin and drive back to her bar in Livingston by Saturday night.',
    'Molly Henderson drove up to Paradise Valley for forty-eight hours to sell her uncle''s cabin and drive back to her bar in Livingston by Saturday night.\n\nInstead she found Sawyer Wrangel on the roof, replacing shingles like he belonged there. Which, inconveniently, he does. Cal rented him the cabin six months ago. Sawyer has a lease through February, a truck under the cottonwoods, and no intention of moving because the woman with the U-Haul and the temper says she has plans.\n\nMolly owns The Bad Penny, a Livingston bar held together by regulars, stubbornness, and whatever she can still fix with her own two hands. Sawyer is a former fire-jumper who walked out of last year''s season and landed in Paradise Valley because quiet looked better than smoke. She picks a fight instead of asking a question. He says he is fine about the one thing he is not fine about. By the time the first frost hits and the cabin''s single bed starts making decisions for them, neither of them is operating on the plan they brought.\n\nBar Fight is Paradise Valley book three: autumn weather, one-bed tension, bar-owner competence, and four explicit scenes for readers of Kristen Ashley, Maisey Yates, and Lauren Landish.',
    '/assets/covers/bar-fight.jpg',
    '978-1-917717-49-6',
    '978-1-917717-50-2',
    '978-1-917717-51-9',
    3,
    true
  )
ON CONFLICT (title_id) DO UPDATE SET
  title = EXCLUDED.title,
  slug = EXCLUDED.slug,
  heteronym = EXCLUDED.heteronym,
  genre = EXCLUDED.genre,
  fiamma_line = EXCLUDED.fiamma_line,
  blurb_short = EXCLUDED.blurb_short,
  blurb_300 = EXCLUDED.blurb_300,
  cover_url = EXCLUDED.cover_url,
  isbn_pb = EXCLUDED.isbn_pb,
  isbn_eb = EXCLUDED.isbn_eb,
  isbn_audio = EXCLUDED.isbn_audio,
  series_order = EXCLUDED.series_order,
  visible = EXCLUDED.visible,
  updated_at = now();
